version: "3.8"

services:

  client:
    container_name: qrobuy-client
    build:
      context: ./qrobuy-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    container_name: qrobuy-server
    build:
      context: ./qrobuy-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongodbnetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - mongodbnetwork
    links:
      - mongo

volumes:
  mongo:

networks:
  mongodbnetwork:
    driver: bridge
